namespace Tonic.Common.OracleHelper.Models.DataPump;

/// <summary>
/// Specifies the method that Import/Export will use to estimate how much disk space each table in the export job will consume (in bytes) or
/// how much data will be generated by an import job (in bytes)
/// </summary>
public enum EstimateMethod
{
    /// <summary>
    /// The estimate is calculated by multiplying the number of database blocks used by the source objects, times the appropriate block sizes.
    /// </summary>
    [Parameter("BLOCKS")]
    Blocks = 0,
    /// <summary>
    /// The estimate is calculated using statistics for each table. For this method to be as accurate as possible, all tables should have been analyzed recently.
    /// (Table analysis can be done with either the SQL ANALYZE statement or the DBMS_STATS PL/SQL package.)
    /// </summary>
    [Parameter("STATISTICS")]
    Statistics
}