[SourceHostSchemaTableRestrictions]
USER_10 = ["TABLE_00"]
USER_11 = ["TABLE_01"]
USER_12 = ["TABLE_02"]
USER_13 = ["TABLE_03"]
USER_14 = ["TABLE_04"]
USER_15 = ["TABLE_05"]
USER_16 = ["TABLE_06"]
USER_17 = ["TABLE_07"]
USER_18 = ["TABLE_08"]
USER_19 = ["TABLE_09"]
USER_20 = ["TABLE_10"]
USER_21 = ["TABLE_11"]